# Generated by Django 4.0.5 on 2022-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFlat',
            fields=[
                ('month', models.TextField(blank=True, null=True)),
                ('town', models.TextField(blank=True, null=True)),
                ('flat_type', models.TextField(blank=True, null=True)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('street_name', models.TextField(blank=True, null=True)),
                ('storey_range', models.TextField(blank=True, null=True)),
                ('floor_area_sqm', models.IntegerField(blank=True, null=True)),
                ('flat_model', models.TextField(blank=True, null=True)),
                ('lease_commence_date', models.IntegerField(blank=True, null=True)),
                ('remaining_lease', models.IntegerField(blank=True, null=True)),
                ('resale_price', models.IntegerField(blank=True, null=True)),
                ('combined_blk_street_name', models.TextField(primary_key=True, serialize=False)),
                ('onemapapi_name', models.TextField(blank=True, db_column='oneMapAPI_Name', null=True)),
                ('time_to_city', models.FloatField(blank=True, null=True)),
                ('nearest_mall', models.IntegerField(blank=True, null=True)),
                ('nearest_school', models.IntegerField(blank=True, null=True)),
                ('nearest_mrt', models.IntegerField(blank=True, null=True)),
                ('storey', models.IntegerField(blank=True, null=True)),
                ('town_premium', models.IntegerField(blank=True, null=True)),
                ('flat_model_premium', models.IntegerField(blank=True, null=True)),
                ('predictedprice', models.FloatField(blank=True, db_column='PredictedPrice', null=True)),
            ],
            options={
                'db_table': 'all_flat',
                'managed': False,
            },
        ),
    ]
